import {test} from 'node:test';import assert from 'node:assert/strict';import {createDesk} from './service.mjs';
function fixture(){let user='writer1',seq=0;const people={writer1:{active:true,role:'writer',name:'Test Writer'},writer2:{active:true,role:'writer',name:'Other Writer'},editor:{active:true,role:'editor',name:'Test Editor'}};const stories=new Map(),events=new Map();
const store={staff:async id=>people[id],getStory:async id=>stories.has(id)?structuredClone(stories.get(id)):null,listStories:async id=>[...stories.values()].filter(s=>!id||s.authorId===id),createStory:async s=>{stories.set(s.id,s);events.set(s.id,[]);return structuredClone(s)},events:async id=>events.get(id),appendEvent:async(id,rev,e)=>{const s=stories.get(id);if(s.revision!==rev)throw Error('CONFLICT');if(e.type==='save'){s.title=e.title;s.body=e.body}if(e.type==='submit')s.status='submitted';if(e.type==='changes_requested')s.status='changes_requested';s.revision++;events.get(id).push(e);return structuredClone(s)}};
const desk=createDesk({identity:{currentMember:async()=>user?{id:user}:null},store,randomId:()=>`id-${++seq}`});return {desk,as:id=>{user=id},people};}
test('anonymous and ordinary subscriber denied',async()=>{const f=fixture();for(const u of [null,'subscriber']){f.as(u);await assert.rejects(f.desk.home(),/NOT_AUTHORIZED/)}});
test('writer creates own draft, ownership payload ignored',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy',authorId:'editor',status:'published'});assert.equal(s.authorId,'writer1');assert.equal(s.status,'draft')});
test('cross-writer draft and conversation access denied',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy'});f.as('writer2');await assert.rejects(f.desk.read(s.id),/NOT_AUTHORIZED/);await assert.rejects(f.desk.reply(s.id,'hello',0),/NOT_AUTHORIZED/);assert.equal((await f.desk.home()).stories.length,0)});
test('revoked staff loses access on the next operation',async()=>{const f=fixture();f.people.writer1.active=false;await assert.rejects(f.desk.create({title:'x',body:''}),/NOT_AUTHORIZED/)});
test('submission freezes copy until editor returns changes',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy'});await f.desk.submit(s.id,0);await assert.rejects(f.desk.save(s.id,{title:'x',body:'y'},1),/READ_ONLY_STATUS/);f.as('editor');await f.desk.requestChanges(s.id,'Please check the date',1);f.as('writer1');const updated=await f.desk.save(s.id,{title:'Headline',body:'Revised copy'},2);assert.equal(updated.body,'Revised copy')});
test('old revision cannot overwrite another edit',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy'});const a=await Promise.allSettled([f.desk.save(s.id,{title:'A',body:'A'},0),f.desk.save(s.id,{title:'B',body:'B'},0)]);assert.equal(a.filter(x=>x.status==='fulfilled').length,1)});
test('writer cannot act as editor',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy'});await f.desk.submit(s.id,0);await assert.rejects(f.desk.requestChanges(s.id,'change',1),/NOT_AUTHORIZED/)});
test('research question is visibly pending, never an invented AI answer',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy'});await f.desk.question(s.id,'Was this the first meeting?',0);const r=await f.desk.read(s.id);assert.equal(r.events[0].state,'awaiting_editor');assert.equal((await f.desk.home()).capabilities.ai,false)});
test('private media unconfigured fails closed',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy'});await assert.rejects(f.desk.upload(s.id,{}),/PRIVATE_UPLOADS_NOT_CONNECTED/)});
test('cross-writer media request rejected before provider use',async()=>{const f=fixture();const s=await f.desk.create({title:'Headline',body:'Copy'});f.as('writer2');await assert.rejects(f.desk.upload(s.id,{}),/NOT_AUTHORIZED/)});
test('input bounds and empty submission rejected',async()=>{const f=fixture();await assert.rejects(f.desk.create({title:'x'.repeat(181),body:''}),/INVALID_INPUT/);const s=await f.desk.create({title:'Headline',body:''});await assert.rejects(f.desk.submit(s.id,0),/NOT_READY/)});
