export function deskAnswer(question:string,context:{title?:string,status?:string,photo?:string,words?:number}={}){const q=question.toLowerCase();
if(/publish|live|newsletter|gmail|email|google|wix/.test(q))return 'This desk collects stories for editorial review. It does not publish to Wix or send a newsletter. Direct Gmail intake and Google sign-in are not connected. Use the private ChatGPT sign-in link to open the desk. An editor can export approved copy, publish it in Wix, then record the live article link here.';
if(/upload|word|docx|document|paste|format/.test(q))return 'Use Upload here under Story file for a .docx file up to 10 MB, or paste into the story box. Word import keeps paragraphs, headings, lists, bold, italics and links; it does not copy the exact page layout. Review the imported text, then save. Embedded Word photos are omitted—upload a picture separately if you want.';
if(/photo|image|art|credit|picture|reserved/.test(q))return 'A picture is optional. Use Upload here under Picture to attach a JPG or PNG up to 10 MB, or leave it blank. Your editor handles photo selection, credit and formatting.';
if(/submit|review|send|finish/.test(q))return 'Add a headline and story, then click Submit at the bottom. No picture is required. Your editor takes care of the rest. Use Save if you want to finish later.';
if(/save|lost|draft|auto|recover/.test(q))return 'Use Save before leaving the story. The Saved label confirms it reached the desk. Your saved drafts appear in My stories and remain available across sessions. Unsaved changes stay in the current page only. If another window changed the story, copy your text before reopening the latest version. The desk preserves previous saved revisions.';
if(/profile|byline|name|bio/.test(q))return 'Open My profile to update your display name, role description and biography. Your saved profile supplies the byline for new stories. Existing stories keep the byline recorded when they were created.';
if(/status|where|my story/.test(q))return context.title?`“${context.title}” is ${context.status||'a draft'} with ${context.words||0} words. Open My stories to see the saved status. Editor notes appear in the story’s Editor notes section.`:'Open My stories for your saved drafts and submission status. Draft means still writing; In review means submitted; Changes requested means an editor has returned it; Approved means ready for an editor to publish in Wix.';
if(/edit|change|locked/.test(q))return 'Drafts and returned stories are editable. Submitted and approved stories are locked to protect the reviewed version. Leave a note asking the editor to return the story if you need to revise it.';
if(/help|hello|hi\b|what can/.test(q))return 'I’m the desk’s built-in help guide. Ask about Word uploads, saving, photos, credits, submissions or your profile. I don’t browse the web or verify sports facts. You can add an unanswered question to an open story for the editor.';
return 'I don’t have a verified answer to that. I’m a portal help guide, not a general AI or live sports fact-checker. If this concerns your story, use Add question to story below so your editor can review it. For portal help, ask about uploads, photos, saving or submitting.';}
