import {db,staffUser,setupUser,storyFor,ok,fail,jsonInput,id,now,runtime} from '@/lib/server';
import {DeskError,text,cleanDelta,mayEdit,transition,photoSelectable} from '@/lib/domain';
import catalog from '@/lib/catalog.json';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const staff=await staffUser();const query=new URL(request.url).searchParams;const storyId=query.get('story');if(storyId){const story=await storyFor(staff,storyId);const notes=await db().prepare('SELECT * FROM notes WHERE story_id = ? ORDER BY created_at').bind(storyId).all();const revisions=await db().prepare('SELECT revision,created_at FROM revisions WHERE story_id = ? ORDER BY revision DESC LIMIT 50').bind(storyId).all();return ok({story,notes:notes.results,revisions:revisions.results});}const stories=staff.role==='editor'?await db().prepare('SELECT * FROM stories ORDER BY updated_at DESC LIMIT 200').all():await db().prepare('SELECT * FROM stories WHERE author_id = ? ORDER BY updated_at DESC LIMIT 200').bind(staff.user_id).all();const photoRows=await db().prepare('SELECT * FROM photos ORDER BY updated_at DESC LIMIT 500').all<any>();const reservations=await db().prepare('SELECT photo_id, story_id FROM reservations').all();const mapped=new Map(catalog.photos.map((p:any)=>[p.id,p]));for(const p of photoRows.results)mapped.set(p.id,p);const team=staff.role==='editor'?await db().prepare('SELECT email,name,role,active,title FROM staff ORDER BY name').all():{results:[]};return ok({staff,stories:stories.results,photos:[...mapped.values()],reservations:reservations.results,team:team.results,catalogDate:catalog.checkedAt});}catch(e){return fail(e)}}
export async function POST(request:Request){try{const p=await jsonInput(request);if(p.action==='initialize')return ok({staff:await setupUser()});const staff=await staffUser();const stamp=now();
if(p.action==='profile'){const name=text(p.name,100,true),bio=text(p.bio,1500),title=text(p.title,100);await db().prepare('UPDATE staff SET name=?,bio=?,title=? WHERE user_id=?').bind(name,bio,title,staff.user_id).run();return ok({saved:true});}
if(p.action==='staff'){if(staff.role!=='editor')throw new DeskError('Only editors can manage the team.',403);const email=text(p.email,200,true).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new DeskError('Enter a valid email address.');if(email===runtime().OWNER_EMAIL?.toLowerCase())throw new DeskError('The publisher’s access is protected.');const name=text(p.name,100,true),role=['writer','editor'].includes(p.role)?p.role:'writer';await db().prepare('INSERT INTO staff(email,name,role,active) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,active=excluded.active').bind(email,name,role,p.active===false?0:1).run();return ok({saved:true});}
if(p.action==='photo'){if(staff.role!=='editor')throw new DeskError('Only editors can clear photos for use.',403);let photo=await db().prepare('SELECT * FROM photos WHERE id=?').bind(p.id).first<any>();photo=photo||catalog.photos.find((x:any)=>x.id===p.id);if(!photo)throw new DeskError('Photo not found.',404);const status=['available','featured','recent','unchecked'].includes(p.status)?p.status:'unchecked';const credit=text(p.credit,200);if(status==='available'&&!credit)throw new DeskError('Add a verified photo credit before making it available.');await db().prepare('INSERT INTO photos(id,name,url,credit,status,last_use,tags,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET credit=excluded.credit,status=excluded.status,updated_at=excluded.updated_at').bind(photo.id,photo.name,photo.url,credit,status,photo.last_use||'',photo.tags||'',photo.source||'wix',stamp).run();return ok({saved:true});}
if(p.action==='create'){const storyId=id();await db().prepare('INSERT INTO stories(id,author_id,byline,created_at,updated_at) VALUES(?,?,?,?,?)').bind(storyId,staff.user_id,staff.name,stamp,stamp).run();return ok({story:await storyFor(staff,storyId)},201);}
const story=await storyFor(staff,text(p.id,100,true));
if(p.action==='note'){const body=text(p.body,4000,true);await db().prepare('INSERT INTO notes(id,story_id,author_id,author_name,body,created_at) VALUES(?,?,?,?,?,?)').bind(id(),story.id,staff.user_id,staff.name,body,stamp).run();return ok({saved:true});}
if(p.revision!==story.revision)throw new DeskError('This story changed in another window. Copy your unsaved text before reopening the latest version.',409);
if(p.action==='save'){if(!mayEdit(staff,story))throw new DeskError('This story is with the editor. Ask for changes to reopen it.',403);const delta=cleanDelta(p.body);const plain=delta.ops.map((x:any)=>x.insert).join('');const title=text(p.title,200),dek=text(p.dek,500),section=text(p.section,60,true),photoId=p.photoId?text(p.photoId,200):null,credit=text(p.photoCredit,200),caption=text(p.caption,1000),artRequest=text(p.artRequest,1000);if(photoId){const photo=await db().prepare('SELECT * FROM photos WHERE id=?').bind(photoId).first<any>()||catalog.photos.find((x:any)=>x.id===photoId);const reservation=await db().prepare('SELECT * FROM reservations WHERE photo_id=?').bind(photoId).first();if(!(photo?.source==='upload'&&(photo.uploaded_by===story.author_id||photo.uploaded_by===staff.user_id))&&!photoSelectable(photo,reservation,story.id))throw new DeskError('That photo is not available. Choose another or ask the editor.');}
const result=await db().batch([db().prepare('INSERT INTO revisions(id,story_id,revision,snapshot,created_at) SELECT ?,id,revision,?,? FROM stories WHERE id=? AND revision=?').bind(id(),JSON.stringify(story),stamp,story.id,story.revision),db().prepare('UPDATE stories SET title=?,dek=?,section=?,body=?,plain=?,photo_id=?,photo_credit=?,caption=?,art_request=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(title,dek,section,JSON.stringify(delta),plain,photoId,credit,caption,artRequest,stamp,story.id,story.revision)]);if(!result[1].meta.changes)throw new DeskError('This story changed. Reopen it before saving.',409);return ok({story:await storyFor(staff,story.id)});}
const next=transition(staff,story,p.action);
if(next==='review'){if(!story.title.trim()||!story.plain.trim())throw new DeskError('Add a headline and story before submitting.');}
const note=typeof p.note==='string'?text(p.note,4000):'';if(next==='changes'&&!note)throw new DeskError('Tell the writer what needs changing.');let publishedUrl='';if(next==='published'){publishedUrl=text(p.url,2000,true);let u;try{u=new URL(publishedUrl)}catch{throw new DeskError('Paste the published article URL.');}if(u.protocol!=='https:'||u.hostname!=='www.gatorbaitmedia.com')throw new DeskError('Use the published GatorBait article link.');}
const statements=[];if(next==='review'&&story.photo_id){const photo=await db().prepare('SELECT * FROM photos WHERE id=?').bind(story.photo_id).first<any>()||catalog.photos.find((x:any)=>x.id===story.photo_id);if(!(photo?.source==='upload'&&(photo.uploaded_by===story.author_id||photo.uploaded_by===staff.user_id))&&(!photo||photo.status!=='available'))throw new DeskError('Your selected photo needs the editor’s approval again.');if(photo?.source!=='upload')statements.push(db().prepare('INSERT INTO reservations(photo_id,story_id,created_at) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM stories WHERE id=? AND revision=?)').bind(story.photo_id,story.id,stamp,story.id,story.revision));}
statements.push(db().prepare('INSERT INTO revisions(id,story_id,revision,snapshot,created_at) SELECT ?,id,revision,?,? FROM stories WHERE id=? AND revision=?').bind(id(),JSON.stringify(story),stamp,story.id,story.revision));statements.push(db().prepare('UPDATE stories SET status=?,revision=revision+1,updated_at=?,published_url=COALESCE(?,published_url) WHERE id=? AND revision=?').bind(next,stamp,publishedUrl||null,story.id,story.revision));const updateIndex=statements.length-1;
if(['changes','published'].includes(next))statements.push(db().prepare('DELETE FROM reservations WHERE story_id=? AND EXISTS(SELECT 1 FROM stories WHERE id=? AND revision=? AND status=?)').bind(story.id,story.id,story.revision+1,next));if(next==='published'&&story.photo_id)statements.push(db().prepare("UPDATE photos SET status='recent',last_use=?,updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM stories WHERE id=? AND revision=? AND status='published')").bind(story.title,stamp,story.photo_id,story.id,story.revision+1));if(note)statements.push(db().prepare('INSERT INTO notes(id,story_id,author_id,author_name,body,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM stories WHERE id=? AND revision=? AND status=?)').bind(id(),story.id,staff.user_id,staff.name,note,stamp,story.id,story.revision+1,next));let result;try{result=await db().batch(statements)}catch(e){if(String(e).includes('UNIQUE'))throw new DeskError('That photo was just reserved for another story. Choose another photo.',409);throw e;}if(!result[updateIndex].meta.changes)throw new DeskError('The story changed. Refresh before trying again.',409);return ok({story:await storyFor(staff,story.id)});
}catch(e){return fail(e)}}
