(function(){
'use strict';
if(window.GBMV2Data)return;
function text(el,sel){if(!el)return'';var n=el.querySelector(sel);return n?(n.textContent||'').trim():'';}
function strip(html,max){var d=document.createElement('div');d.innerHTML=html||'';var s=(d.textContent||'').replace(/\s+/g,' ').trim();if(max&&s.length>max)s=s.slice(0,max).replace(/[\s,;:.!—-]+$/,'')+'…';return s;}
function creator(item){var ns=item.getElementsByTagNameNS?item.getElementsByTagNameNS('*','creator'):[];if(ns&&ns[0])return(ns[0].textContent||'').trim()||'GatorBait Staff';return text(item,'creator')||'GatorBait Staff';}
function image(item){var e=item.querySelector('enclosure');if(e&&e.getAttribute('url'))return e.getAttribute('url');var nodes=item.getElementsByTagName('*');for(var i=0;i<nodes.length;i++){var n=nodes[i],name=(n.localName||n.nodeName||'').toLowerCase();if((name==='content'||name==='thumbnail')&&n.getAttribute&&n.getAttribute('url'))return n.getAttribute('url');}var desc=text(item,'description'),m=desc.match(/<img[^>]+src=["']([^"']+)/i);return m?m[1]:'';}
function category(item,title){var cats=[];if(item){var nodes=item.querySelectorAll('category');for(var i=0;i<nodes.length;i++)cats.push((nodes[i].textContent||'').toLowerCase());}var hay=(cats.join(' ')+' '+(title||'')).toLowerCase();if(/recruit|commit|prospect|portal/.test(hay))return'Recruiting';if(/basketball|hoops/.test(hay))return'Basketball';if(/baseball|diamond/.test(hay))return'Baseball';return'Football';}
function normalizeFixture(rows){return rows.map(function(p,i){var d=p.date instanceof Date?p.date:new Date(p.date||Date.now()-i*3600000);return{title:p.title||'Untitled',desc:p.desc||'',link:p.link||'#',img:p.img||'',who:p.who||'GatorBait Staff',date:d,category:p.category||category(null,p.title)};}).sort(function(a,b){return b.date-a.date;});}
function fromXml(xml){var doc=new DOMParser().parseFromString(xml,'application/xml');var items=Array.prototype.slice.call(doc.querySelectorAll('item'));return items.map(function(item){var title=text(item,'title'),raw=text(item,'pubDate'),link=text(item,'link').replace(/^https?:\/\/[^/]+/i,'');return{title:title,desc:strip(text(item,'description'),260),link:link||'#',img:image(item),who:creator(item),date:raw?new Date(raw):new Date(0),category:category(item,title)};}).filter(function(p){return p.title&&/^\/post\//.test(p.link);}).sort(function(a,b){return b.date-a.date;}).slice(0,50);}
function load(){if(Array.isArray(window.__GBM_V2_FIXTURE__))return Promise.resolve(normalizeFixture(window.__GBM_V2_FIXTURE__));return fetch('/blog-feed.xml?gbm-v2='+Date.now(),{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('feed '+r.status);return r.text();}).then(fromXml);}
window.GBMV2Data={load:load,strip:strip};
})();